import type { Rarity } from '@prisma/client';

export interface SeedCard {
  name: string;
  slug: string;
  rarity: Rarity;
  description: string;
  lore: string;
  attack: number;
  defense: number;
  abilityName: string;
  abilityDescription: string;
  imageUrl: string;
  collectionNumber: number;
  active: boolean;
}

type CardDraft = [
  string,
  Rarity,
  string,
  string,
  number,
  number,
  string,
  string,
];
const drafts: CardDraft[] = [
  [
    'Ari Vale',
    'COMMON',
    'A bright courier who races along comet trails.',
    'Ari maps safe paths between drifting sky-isles for anyone brave enough to follow.',
    18,
    22,
    'Comet Dash',
    'Gains momentum while shielding a nearby traveler.',
  ],
  [
    'Mossbit Taro',
    'COMMON',
    'A gentle gardener with a clockwork watering can.',
    'Taro raises tiny moon-gardens in the abandoned stations of the outer ring.',
    12,
    29,
    'Sprout Guard',
    'Summons luminous vines into a protective screen.',
  ],
  [
    'Pippa Volt',
    'COMMON',
    'An upbeat mechanic powered by pocket lightning.',
    'Pippa repairs star-skiffs with cheerful inventions assembled from harmless scrap.',
    24,
    16,
    'Spark Patch',
    'Restores a device with a precisely aimed electric pulse.',
  ],
  [
    'Nim Cloudstep',
    'COMMON',
    'A quiet scout who walks on condensed mist.',
    'Nim listens for distant storms and guides villages away from their path.',
    20,
    21,
    'Mist Tread',
    'Vanishes into a cool veil and reappears one step ahead.',
  ],
  [
    'Juniper Koi',
    'COMMON',
    'A river guardian with a paper-fin cloak.',
    'Juniper carries wishes downstream so forgotten hopes can reach the sea of stars.',
    17,
    26,
    'Wish Current',
    'Turns a hopeful thought into a steady defensive current.',
  ],
  [
    'Kellan Bramble',
    'COMMON',
    'A steadfast ranger from the thornwood moons.',
    'Kellan befriends every strange creature encountered beneath the violet canopy.',
    23,
    24,
    'Briar Brace',
    'Raises a woven barrier that softens incoming force.',
  ],
  [
    'Sumi Lantern',
    'COMMON',
    'A night-market guide bearing a friendly blue flame.',
    'Sumi ensures no festival visitor becomes lost when the twin moons disappear.',
    15,
    28,
    'Beacon Bloom',
    'Illuminates hidden paths and steadies uncertain allies.',
  ],
  [
    'Rook Pebbleheart',
    'COMMON',
    'A small stone sentinel with enormous resolve.',
    'Rook woke beneath an ancient bridge and vowed to protect every crossing.',
    21,
    30,
    'Granite Promise',
    'Plants firmly in place and refuses to yield.',
  ],
  [
    'Vela Thistledown',
    'UNCOMMON',
    'A wind duelist whose ribbons predict every gust.',
    'Vela studies the language of air above the floating saffron fields.',
    34,
    27,
    'Gale Script',
    'Draws a ribbon sigil that redirects an incoming strike.',
  ],
  [
    'Orin Echofox',
    'UNCOMMON',
    'A masked soundweaver followed by spectral foxlights.',
    'Orin records vanishing songs before silence can erase their memory.',
    31,
    30,
    'Resonant Pack',
    'Echoes a melody through several phantom companions.',
  ],
  [
    'Maeve Gearwing',
    'UNCOMMON',
    'An aviator with hand-built copper wings.',
    'Maeve crosses impossible ravines to deliver medicine to isolated observatories.',
    36,
    25,
    'Copper Updraft',
    'Catches a thermal burst and lifts the whole squad.',
  ],
  [
    'Tenzin Ripple',
    'UNCOMMON',
    'A patient martial artist who bends reflected light.',
    'Tenzin trains beside mirror lakes where every motion answers with another.',
    33,
    33,
    'Mirror Palm',
    'Returns a measured portion of an opponent’s force.',
  ],
  [
    'Cira Emberloom',
    'UNCOMMON',
    'A textile mage weaving warmth into battle cloaks.',
    'Cira learned to spin sunrise fibers after her mountain town lost its summer.',
    29,
    38,
    'Hearthweave',
    'Wraps allies in cloth that glows with enduring heat.',
  ],
  [
    'Bram Starling',
    'UNCOMMON',
    'A daring navigator guided by mechanical birds.',
    'Bram charts moving constellations from the deck of a tiny solar sailboat.',
    39,
    26,
    'Flock Compass',
    'His starling swarm reveals the safest route forward.',
  ],
  [
    'Iona Prismark',
    'RARE',
    'A crystal archer who splits moonbeams into arrows.',
    'Iona guards the glass desert where buried colors awaken after dusk.',
    51,
    38,
    'Sevenfold Volley',
    'Divides one radiant shot into seven precise streaks.',
  ],
  [
    'Kael Hollowbell',
    'RARE',
    'A wandering guardian whose bell calms wild spirits.',
    'Kael carries a bell forged from a peaceful meteor and rings it only for mercy.',
    44,
    49,
    'Tranquil Toll',
    'Stillness spreads outward, weakening hostile intent.',
  ],
  [
    'Nyra Flux',
    'RARE',
    'A gravity skater tracing luminous rings in space.',
    'Nyra turned an abandoned orbital highway into the galaxy’s boldest racecourse.',
    55,
    35,
    'Orbit Break',
    'Slingshots around a gravity well for a dazzling impact.',
  ],
  [
    'Solenne Rainquill',
    'RARE',
    'A storm poet whose verses become silver birds.',
    'Solenne writes above thunderheads to preserve the secret names of rain.',
    47,
    46,
    'Tempest Verse',
    'A spoken stanza calls down a focused curtain of rain.',
  ],
  [
    'Dax Moonforge',
    'RARE',
    'A lunar smith carrying a crescent-shaped hammer.',
    'Dax tempers tools in cold moonfire for explorers who cannot return home.',
    50,
    48,
    'Crescent Temper',
    'Strengthens armor with a ringing arc of pale flame.',
  ],
  [
    'Elara Sunshear',
    'EPIC',
    'A radiant knight who cuts shadows from the dawn.',
    'Elara keeps watch at the horizon gate, where unfinished nights gather.',
    67,
    56,
    'Daybreak Sever',
    'Cleaves through darkness and leaves a protective afterglow.',
  ],
  [
    'Kiro Dreamtide',
    'EPIC',
    'A lucid sailor navigating oceans made of dreams.',
    'Kiro rescues sleepers stranded among reefs of old fears and fading memories.',
    61,
    63,
    'Waking Wave',
    'Rolls a lucid tide that carries companions beyond fear.',
  ],
  [
    'Zella Runebloom',
    'EPIC',
    'An arcane botanist growing constellations from seeds.',
    'Zella’s greenhouse contains infant stars that hum when their names are spoken.',
    58,
    70,
    'Nebula Garden',
    'A cosmic flower opens and fortifies the surrounding ground.',
  ],
  [
    'Riven Aetherclaw',
    'EPIC',
    'A sky hunter bonded to a translucent cloud-lion.',
    'Riven and their companion patrol the border between weather and wilderness.',
    72,
    53,
    'Aether Pounce',
    'The pair descends as one streak of roaring blue wind.',
  ],
  [
    'Astrid Crownflare',
    'LEGENDARY',
    'A sovereign protector crowned by a miniature sun.',
    'Astrid ended the century eclipse by sharing her crown’s fire with seven cities.',
    82,
    76,
    'Sovereign Dawn',
    'Unfurls a golden horizon that rallies every ally.',
  ],
  [
    'Zephyr Nightglass',
    'LEGENDARY',
    'A master spy moving through reflections of starlight.',
    'Zephyr safeguards the names of hidden worlds within an unbreakable black mirror.',
    86,
    69,
    'Midnight Refraction',
    'Steps through one reflection and strikes from another.',
  ],
  [
    'Oryn Titanwake',
    'LEGENDARY',
    'A calm giant who awakens sleeping celestial engines.',
    'Oryn hears machinery beneath planets and repairs it with patient thunder.',
    79,
    85,
    'Worldgear Pulse',
    'Restarts an ancient mechanism with one resonant blow.',
  ],
  [
    'Lyra Eternova',
    'MYTHIC',
    'An immortal songkeeper carrying the first melody.',
    'Lyra sings at the edge of time so each new universe begins in harmony.',
    92,
    88,
    'Genesis Chorus',
    'The opening note renews courage and reshapes the battlefield.',
  ],
  [
    'Caelum Voidbloom',
    'MYTHIC',
    'A serene wanderer cultivating flowers in empty space.',
    'Caelum proved that even the deepest void can shelter color, fragrance, and life.',
    89,
    94,
    'Infinite Petal',
    'A boundless blossom absorbs despair and releases hope.',
  ],
  [
    'Seraphine Starweft',
    'MYTHIC',
    'A celestial tailor mending tears in the night sky.',
    'Seraphine stitches fallen constellations back into their rightful stories.',
    95,
    87,
    'Fateweave Mantle',
    'Repairs a broken possibility with threads of living light.',
  ],
  [
    'Nova Kaleidos',
    'RAINBOW',
    'A prism dancer whose steps paint new dimensions.',
    'Nova discovered that every color is a doorway and every dance can open one.',
    98,
    96,
    'Spectrum Ascension',
    'Seven colors spiral together into an unstoppable aurora.',
  ],
  [
    'Eiko Chromasoul',
    'RAINBOW',
    'A harmonious guardian embodying the full cosmic spectrum.',
    'Eiko unites rival star-clans by revealing the shared light within their banners.',
    96,
    99,
    'Unity Radiance',
    'Blends many strengths into one brilliant, sheltering wave.',
  ],
  [
    'The Last Lucent',
    'SECRET',
    'A nameless keeper waiting beyond the final constellation.',
    'Legends say the Lucent remembers every kindness performed when nobody watched.',
    100,
    100,
    'Unwritten Tomorrow',
    'Reveals a path that exists only for those who still choose hope.',
  ],
];

const slugify = (name: string) =>
  name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
export const cardSeedData: SeedCard[] = drafts.map(
  (
    [
      name,
      rarity,
      description,
      lore,
      attack,
      defense,
      abilityName,
      abilityDescription,
    ],
    index,
  ) => ({
    name,
    slug: slugify(name),
    rarity,
    description,
    lore,
    attack,
    defense,
    abilityName,
    abilityDescription,
    imageUrl: `/card-art/${slugify(name)}.webp`,
    collectionNumber: index + 1,
    active: true,
  }),
);
